
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glvohakzjiruwnunngqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsdm9oYWt6amlydXdudW5uZ3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Njg0ODIsImV4cCI6MjA1NjM0NDQ4Mn0.fhk28xbyEgZYseHnldkQDEX-1aP3CmVWLCwwp9WZGYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
